### ISSUE TITLE
Support mDNS .local names for each minimesos container

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#257]
It would be a cool feature of minimesos if we were able to register services using DNS names on the developer's machine. The user of minimesos would no longer have to work with IP addresses of containers but use names that are friendly and don't change. E.g. `marathon.mycluster.local`

Dynamically registering DNS names in the system seems only to be possible using Multicast DNS or editing the hosts file. Both options have their pros and cons:
- **Hosts file**: Simple solution, but needs admin rights to modify hosts file. As services are started and stopped all the time it could become very annoying to the user.
- **Multicast DNS**: Dynamic and programmable but also a hack. mdns isn't designed to register dns names on local host but to broadcast services over the LAN. This has some consequences (see below).

From the two options we went for Multicast DNS. There are several ways to use that one too:
- **Use the multicast daemon available on the host OS**: Both Linux and OSX have multicast daemon processes that can be controlled from the command line. There is `avahi` in Linux and `dns-sd` on OSX and no equivalent on Windows. The good thing is that both `avahi` and `dns-sd` are capable to advertise any IP address as service endpoint. In this scenario we are depending on the fact that if we use one of the daemons to advertise a service they will register it on the host which they are running on. Meaning that we will be advertising over the whole LAN but just care about the service registering on the local machine.
- **Use OS-independent multicast server**: We tried to work with a NodeJS implementation called [Bonjour](https://github.com/watson/bonjour). This would be a much cleaner solution then using native command line utilities but we ran into an interesting problem: you cannot specify the IP address of the service using `bonjour`, it assumes you want to advertise a service running on the local machine where the server is running. This is a valid assumption on the part of the implementor of the library as that is how things work normally. I looked around quite a bit in search for another library but didn't find anything. Fortunately we are not bound to Javascript in any way for this service (thanks Docker) so we can still try to find something written in another language. There is an important assumption in this setup that we didn't test yet - if an mdns server running locally advertises a new service on the network this gets picked up by the local mdns daemon and gets registered. I'm realising as I'm writing this that the fact that Windows doesn't have an mdns daemon will prevent this solution from working too.

In any case the idea is to implement the solution as a new container that will be part of minimesos (started with the rest of the cluster) and listens to Docker events. It would be ideal to package it as a Docker container so we can install it the same way as the other services.
# Example with `avahi`

Register the master container for minimesos cluster called 'cluster'. 

```
$ avahi-publish-address -a master.cluster.local 172.17.0.4
Established under name 'master.cluster.local'
```

Now use the registered hostname mapping

```
$ curl -s master.cluster.local:5050/state.json | jq  .version
"0.25.0"
```

**Comment by frankscholten** [comment]
Useful for https://github.com/ContainerSolutions/minimesos/issues/188

**Comment by frankscholten** [comment]
Closing as this idea will be explored in https://github.com/ContainerSolutions/minimesos-mdns

**Comment by frankscholten** [comment]
## Multicast versus DBus

The avahi commands mentioned earlier cannot easily be run from a container since they use the DBus API. 

I started looking for a program that uses multicast and I found the [ruby mdns gem](https://github.com/tenderlove/dnssd). With this gem you can register `.local` domain names for a given IP and a TTL.

## Example

Create the file `main.rb`

```
require "mdns"

MDNS.add_record("test.local", 60, "127.0.0.1") # Add a record for leet.local to resolve to 10.0.13.37 with a TTL of 60 seconds
MDNS.start
```
Now run the program to register the `test.local` domain.

```
$ sudo gem install mdns
$ ruby main.rb
$ ping test.local
PING test.local (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.029 ms
^C
--- test.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.028/0.028/0.029/0.005 ms
````

## TODO

- [ ] Install ruby on the minimesos cli Docker container
- [ ] Create a ruby script that can be called from the minimesos cli container using a `ProcessBuilder`
- [ ] The ruby script should have support for registering and deregistering records
- [ ] In `AbstractContainer` add code to register and deregister records when containers are started and destroyed
- [ ] Add error handling in case there is no mDNS responder like Avahi or Bonjour running

**Comment by frankscholten** [comment]
We now support Mesos DNS + dnsmasq so this is no longer necessary.
