### ISSUE TITLE
Support IP per container

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#420]
Currently Marathon and Mesos expect containers to use the host network stack. Minimesos however runs in containers and uses separate network stacks which causes https://github.com/ContainerSolutions/minimesos/issues/401.

Let's support IP per container http://mesos.apache.org/documentation/latest/networking-for-mesos-managed-containers and http://mesos.apache.org/documentation/latest/networking-for-mesos-managed-containers to solve this.

To support this we have to add Mesos Calico network isolation module.

**TODO**

- [ ] Support Calico network isolation Mesos module. We can either add this into our default image or use the Docker API to build a child image that includes a module just before launching the cluster
- [ ] Generate default `minimesos` configuration that adds Calico module
- [ ] Add system test

**Comment by frankscholten** [comment]
# CNI Support + host local plugin

To keep things simple let's focus first on enabling CNI and configure the [host-local IP address manager](https://github.com/containernetworking/cni/tree/master/plugins/ipam/host-local)(IPAM). Once that works we can support more complex technologies.

# TODO

- [ ] Add CNI config + `host-local` plugin to the Mesos Agent image
- [ ] Release Mesos Agent image to Docker Hub
- [ ] Update the Mesos Agent image version in minimesos config
- [ ] Add an example app in the default Marathon file that demonstrates IP per task functionality
